@Library('shared-library') _

pipeline {
    agent {
        kubernetes {
            yamlFile 'KubernetesPod.yaml'
        }
    }
	stages {
		stage('初始化') {
			steps {
                container('jnlp') {
                    println('jnlp:' + pwd())
                }
				 container('docker-build'){
				 	script{
						runWrapper.loadJSON('/jenkins-project.json')
						runWrapper.runSteps('初始化')
						runWrapper.printEnvVars()
					}
				}
			}
		}
		stage('单元测试') {
			steps {
				 container('docker-build'){
				 	script{
						runWrapper.runSteps('单元测试')
					}
				}
			}
		}
        stage('代码检查') {
			steps {
				 container('docker-build'){
				 	script{
				 		runWrapper.runSteps('代码检查')
				 	}
				}
			}
		}
		stage('编译构建') {
			steps {
				 container('docker-build'){
				 	script{
						runWrapper.runSteps('编译构建')
					}
				}
			}
		}
		stage('部署') {
			steps {
				 container('docker-build'){
				 	script{
						runWrapper.runSteps('部署')
					}
				}
			}
		}
	}
}