apiVersion: "v1"
kind: "Pod"
metadata:
spec:
  containers:
    - name: "docker-build"
      image: "docker.io/alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47"
      command:
        - "cat"
      tty: true
      workingDir: "/home/jenkins/agent"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
  securityContext:
    seccompProfile:
      type: RuntimeDefault
