ARG ANDROID_BASE_IMAGE=ghcr.io/cirruslabs/android-sdk:36@sha256:f9b3ea9ed2b5fc9522adae82c7b4622ab7aa54207ef532c8e615a347dca08f31
FROM ${ANDROID_BASE_IMAGE}

COPY --chmod=0555 aapt2 /opt/android-sdk-linux/build-tools/36.0.0/aapt2
