@Library('shared-library') _

pipeline {
	agent { label params['agent-name'] }
	parameters { //定义构建参数
		choice choices: ['-'], description: '请选择要部署的项目', name: 'Deploy_Choice'
		agentParameter name:'agent-name'
		checkboxParameter name:'project-list', format:'YAML', uri:'https://raw.githubusercontent.com/sunweisheng/jenkins-json-build/master/example/microservice-build/project-list.yaml'
	}
	stages {
		stage('初始化') {
			steps {
				script{
					runWrapper.loadJSON(params['project-list'])
					runWrapper.runSteps('初始化')
				}
			}
		}
		stage('单元测试') {
			steps {
				script{
					runWrapper.runSteps('单元测试')
				}
			}
		}
		stage('代码检查') {
			steps {
				script{
					runWrapper.runSteps('代码检查')
				}
			}
		}
		stage('编译构建') {
			steps {
				script{
					runWrapper.runSteps('编译构建')
				}
			}
		}
		stage('部署') {
			steps {
				script{
					runWrapper.runStepForEnv('部署','Deploy_Choice')
				}
			}
		}
	}
}