@Library('shared-library') _

pipeline {
	agent any
	stages {
		stage('处理过程1') {
			steps {
				script{
					Exception ex
					runWrapper.loadJSON('/jenkins-project.json')
				}
			}
		}
		stage('处理过程2') {
        	steps {
        		script{
        			println('处理过程2')
        			try{
        				throw new Exception('模拟异常')
        			}catch(Exception e){
        				ex = e
        				throw e
        			}
        		}
        	}
        }
		stage('处理过程3') {
			steps {
				script{
					println('处理过程3')
				}
			}
		}
	}
	post {
            failure {
            	script{
                	runWrapper.postFailure(ex)
                }
            }
            success{
            	script{
                	runWrapper.postSuccess()
                }
            }
        }
}